Repository Noviv/BismarkUnchained, pull requests merged in 2019-12, with the labels that each got.

#62 Scalable/tiled space background
  BismarkUnchained/images/background.jpg
  BismarkUnchained/images/background.jpg.import
  BismarkUnchained/scenes/Main/Main.tscn
Labels: UI

#60 Add basic shield and asset
  BismarkUnchained/images/shield.png
  BismarkUnchained/images/shield.png.import
  BismarkUnchained/scenes/Weapons/Shield/Shield.tscn
Labels: player

#61 Explanation screen
  BismarkUnchained/scenes/UI/StartScreen.tscn
Labels: UI

#65 added square wave formation and 'fixed' the logo
  BismarkUnchained/images/bismark_unchained.png
  BismarkUnchained/scenes/WaveHandler/Spawner.gd
  BismarkUnchained/scenes/WaveHandler/WaveHandler.gd
  BismarkUnchained/scenes/Weapons/Bullet/Bullet.gd
Labels: UI, enemy

#67 fix thing
  BismarkUnchained/scenes/Weapons/BulletMine/BulletMine.gd
Labels: bug

#69 random enemy types
  BismarkUnchained/scenes/Main/Main.tscn
  BismarkUnchained/scenes/WaveHandler/Spawner.gd
Labels: enemy

#73 Scrolling background
  BismarkUnchained/scenes/Main/Main.gd
  BismarkUnchained/scenes/Main/Main.tscn
  BismarkUnchained/scenes/Player/Player.gd
  BismarkUnchained/scenes/Player/Player.tscn
  BismarkUnchained/scenes/Wall/Wall.tscn
  BismarkUnchained/scenes/WaveHandler/WaveHandler.gd
Labels: UI, player
