Repository Noviv/BismarkUnchained, pull requests merged in 2019-11, with the labels that each got.

#4 Global state
  BismarkUnchained/project.godot
  BismarkUnchained/scenes/Main.tscn
  BismarkUnchained/scenes/Main/Main.gd
  BismarkUnchained/scenes/Main/Main.tscn
Labels: enhancement

#10 Ui
  BismarkUnchained/project.godot
  BismarkUnchained/scenes/KinematicBody2D.gd
  BismarkUnchained/scenes/Main/Main.gd
  BismarkUnchained/scenes/Main/Main.tscn
  BismarkUnchained/scenes/UI/InGameUI.tscn
  BismarkUnchained/scenes/UI/PauseScene.gd
  BismarkUnchained/scenes/UI/PauseScene.tscn
  BismarkUnchained/scenes/UI/StartButton.gd
  BismarkUnchained/scenes/UI/StartScreen.tscn
Labels: enhancement

#11 Create a simple bullet scene and implement exploding behavior
  BismarkUnchained/scenes/Bullet/Body.gd
  BismarkUnchained/scenes/Bullet/Bullet.gd
  BismarkUnchained/scenes/Bullet/Bullet.tscn
Labels: enhancement

#15 Switch from bullet damage signal to function call
  BismarkUnchained/scenes/Bullet/Body.gd
  BismarkUnchained/scenes/Bullet/Bullet.tscn
  BismarkUnchained/scenes/Enemy/Enemy.gd
  BismarkUnchained/scenes/KinematicBody2D.gd
Labels: enhancement

#8 player movement with wasd. acceleration and velocity working
  BismarkUnchained/project.godot
  BismarkUnchained/scenes/KinematicBody2D.gd
Labels: enhancement

#25 Add an overlay for player health
  BismarkUnchained/scenes/Main/Main.tscn
  BismarkUnchained/scenes/UI/InGameUI.tscn
Labels: UI

#24 Advanced player controls
  BismarkUnchained/scenes/Enemy/Enemy.gd
  BismarkUnchained/scenes/Main/Main.gd
  BismarkUnchained/scenes/Player/KinematicBody2D.gd
  BismarkUnchained/scenes/Player/Player.gd
  BismarkUnchained/scenes/Player/Player.tscn
Labels: player

#26 Add time-delta-scaling to bullet animations
  BismarkUnchained/scenes/Bullet/Body.gd
  BismarkUnchained/scenes/Bullet/Bullet.gd
  BismarkUnchained/scenes/Bullet/Bullet.tscn
Labels: time-delta

#28 Clean ui
  BismarkUnchained/images/bismark_unchained.png
  BismarkUnchained/images/bismark_unchained.png.import
  BismarkUnchained/images/icon.png
  BismarkUnchained/project.godot
  BismarkUnchained/scenes/UI/Exit.gd
  BismarkUnchained/scenes/UI/InGameUI.tscn
  BismarkUnchained/scenes/UI/StartButton.gd
  BismarkUnchained/scenes/UI/StartScreen.tscn
Labels: UI

#30 Enemy
  BismarkUnchained/scenes/Bullet/Bullet.tscn
  BismarkUnchained/scenes/Enemy/Enemy.gd
Labels: enemy

#31 Working alpha level shooting
  BismarkUnchained/project.godot
  BismarkUnchained/scenes/Main/Main.gd
  BismarkUnchained/scenes/Player/Player.gd
  BismarkUnchained/scenes/Player/Player.tscn
Labels: backend, player

#32 Waves
  BismarkUnchained/scenes/Enemy/Enemy.gd
  BismarkUnchained/scenes/Main/Main.gd
  BismarkUnchained/scenes/Main/Main.tscn
  BismarkUnchained/scenes/UI/InGameUI.tscn
  BismarkUnchained/scenes/UI/StartScreen.tscn
  BismarkUnchained/scenes/WaveHandler/Spawner.gd
  BismarkUnchained/scenes/WaveHandler/Spawner.tscn
  BismarkUnchained/scenes/WaveHandler/WaveHandler.gd
  BismarkUnchained/scenes/WaveHandler/WaveHandler.tscn
Labels: UI, enemy

#40 Add transparent Hal texture and change hitbox
  BismarkUnchained/images/hal.png
  BismarkUnchained/images/hal.png.import
  BismarkUnchained/scenes/Player/Player.gd
  BismarkUnchained/scenes/Player/Player.tscn
Labels: backend, bug, player

#41 Add time delta UI on right of screen
  BismarkUnchained/scenes/Main/Main.gd
  BismarkUnchained/scenes/UI/InGameUI.tscn
Labels: UI

#57 Basic upgrades
  BismarkUnchained/scenes/Player/Player.gd
  BismarkUnchained/scenes/UI/StartScreen.tscn
  BismarkUnchained/scenes/UI/Upgrades.gd
  BismarkUnchained/scenes/UI/Upgrades.tscn
  BismarkUnchained/scenes/UI/UpgradesButton.gd
Labels: UI, player

#58 Add mines and fix/improve bullet mechanics
  BismarkUnchained/scenes/Enemy/Enemy.gd
  BismarkUnchained/scenes/Weapons/Bullet/Body.gd
  BismarkUnchained/scenes/Weapons/Bullet/Bullet.gd
  BismarkUnchained/scenes/Weapons/Bullet/Bullet.tscn
  BismarkUnchained/scenes/Weapons/BulletMine/BulletMine.gd
  BismarkUnchained/scenes/Weapons/BulletMine/BulletMine.tscn
  BismarkUnchained/scenes/Weapons/ImpulseMine/ImpulseMine.gd
  BismarkUnchained/scenes/Weapons/ImpulseMine/ImpulseMine.tscn
  BismarkUnchained/scenes/Weapons/Laser/Laser.gd
  BismarkUnchained/scenes/Weapons/Laser/Laser.tscn
Labels: backend, enemy, player

#59 Add real player texture and convex shape
  BismarkUnchained/images/character.png
  BismarkUnchained/images/character.png.import
  BismarkUnchained/images/hal.png
  BismarkUnchained/scenes/Player/Player.tscn
Labels: UI, player
